// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf6mV_N6cqxwHOYRkvtgeaNNyEndBBHMI',
    appId: '1:964467465290:web:0ab122cb17c8d3afaf1ab3',
    messagingSenderId: '964467465290',
    projectId: 'fir-auth-663be',
    authDomain: 'fir-auth-663be.firebaseapp.com',
    storageBucket: 'fir-auth-663be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8rPo4KtRdOD37THR2DFWswNTuAdNahxY',
    appId: '1:964467465290:android:6705b98ce2a444ecaf1ab3',
    messagingSenderId: '964467465290',
    projectId: 'fir-auth-663be',
    storageBucket: 'fir-auth-663be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBv98laph8kvPM230xd_XcyCPaa4LGrGY',
    appId: '1:964467465290:ios:64bb0b136f53f2ddaf1ab3',
    messagingSenderId: '964467465290',
    projectId: 'fir-auth-663be',
    storageBucket: 'fir-auth-663be.firebasestorage.app',
    iosBundleId: 'com.example.agroconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBv98laph8kvPM230xd_XcyCPaa4LGrGY',
    appId: '1:964467465290:ios:64bb0b136f53f2ddaf1ab3',
    messagingSenderId: '964467465290',
    projectId: 'fir-auth-663be',
    storageBucket: 'fir-auth-663be.firebasestorage.app',
    iosBundleId: 'com.example.agroconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf6mV_N6cqxwHOYRkvtgeaNNyEndBBHMI',
    appId: '1:964467465290:web:99f915f9cdd17c7baf1ab3',
    messagingSenderId: '964467465290',
    projectId: 'fir-auth-663be',
    authDomain: 'fir-auth-663be.firebaseapp.com',
    storageBucket: 'fir-auth-663be.firebasestorage.app',
  );
}
